#pragma once

#define CGameObject__OBJECT_TYPE_GUI 0x1
#define CGameObject__OBJECT_TYPE_TILE 0x2
#define CGameObject__OBJECT_TYPE_MODULE 0x3
#define CGameObject__OBJECT_TYPE_AREA 0x4
#define CGameObject__OBJECT_TYPE_CREATURE 0x5
#define CGameObject__OBJECT_TYPE_ITEM 0x6
#define CGameObject__OBJECT_TYPE_TRIGGER 0x7
#define CGameObject__OBJECT_TYPE_PROJECTILE 0x8
#define CGameObject__OBJECT_TYPE_PLACEABLE 0x9
#define CGameObject__OBJECT_TYPE_DOOR 0xA
#define CGameObject__OBJECT_TYPE_AREAOFEFFECTOBJECT 0xB
#define CGameObject__OBJECT_TYPE_WAYPOINT 0xC
#define CGameObject__OBJECT_TYPE_ENCOUNTER 0xD
#define CGameObject__OBJECT_TYPE_STORE 0xE
#define CGameObject__OBJECT_TYPE_PORTAL 0xF
#define CGameObject__OBJECT_TYPE_SOUND 0x10

struct CNWSObject{

};